version: "2"
services:
    db:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        expose: 
            - "3306"
        environment:
            - MYSQL_DATABASE=deploy
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    app:
        build: .
        container_name: deploy_api
        links:
            - db
        ports:
            - "5000:5000"
        depends_on: 
            - db